export {
  Table,
  TableBody,
  type TableBodyProps,
  TableCaption,
  type TableCaptionOwnProps,
  type TableCaptionProps,
  TableCell,
  type TableCellOwnProps,
  type TableCellProps,
  TableContainer,
  type TableContainerProps,
  TableFooter,
  type TableFooterProps,
  TableHead,
  TableHeader,
  type TableHeaderProps,
  type TableHeadProps,
  type TableOwnProps,
  type TableProps,
  TableRow,
  type TableRowOwnProps,
  type TableRowProps,
} from "./table";
